### PR TITLE
Initial commit : Added SaAgentReference for consistency with PayeAgentReference

### PR DESCRIPTION
**Pull request by rahulbaphana**
jira link : https://jira.tools.tax.service.gov.uk/browse/AOSS-641

### CODE REVIEW

**Comment by duncancrawford** [comment]
Should PayeAgentReference or SaAgentReference even be in here?

I am worried this is becoming a dumping ground

**Comment by davesammut** [comment]
They are both TaxIdentifiers that form part of the Auth footprint. The identifier for an agent enrolment is different from that of the clients' enrolments data type. 
For example:
EPAYE:
client => EMPREF (xxx/yyyy)
agent => 12345678890 (string, no structure)

This prevents us from reusing the Account classes for agent enrolments. 

We could go with a not as strongly typed approach and have the variables in the Agent class named accordingly but using the same TaxIdentifier type e.g Uar (which is used by TaxsAgent). 

So, the motivation for putting these agent types in Domain.
1. They are part of the Auth Accounts data type
2. They extend TaxIdentifier 
3. Consistent location for types that are used as part of the  Auth footprint
4. Consistent patterns for dealing with identifiers

**Comment by SteveSmithTech** [comment]
@davesammut Is this still needed?

**Comment by davesammut** [comment]
Yes it is needed, not only for SA Cleanse and Validate but also for Portal
SA-Filing rehoming.

I was thinking that these enrolment identifiers actually replace the
currently used Agent Code id as these might be too generic moving forward.

Capturing and using this level of enrolment data gives aligns MDTP with
HMRC generated identifiers rather than those generated at GGW. I recommend
applying this PR but ensuring that we have a broader discussion in the
context the future of GGW.

Happy to discuss.

**Pull request merged**
