### PR TITLE
Cross build to scala 2.12 with dependecy update

### PR DESCRIPTION
**Pull request by bambuchaAdm**
Domain is one of most important library in HMRC and many teams use it to build their own model libraries. For support for 2.12 on platform, right after cross compiled `auth-client`, - having cross compiled version of `domain` is key. 

@konradwudkowski what do you thing about "play-json" scope change form "provided" to "direct"

### CODE REVIEW

**Review by konradwudkowski — CHANGES_REQUESTED** [review]
+1 for not using `provided`

I'm not an owner of this library but if I was I would expect it to be cross-compiled for play 2.5 and 2.6 and not simply upgraded to 2.6. And then there doesn't seem to be any breaking changes so it could stay at major version 5?

**Comment by bambuchaAdm** [comment]
@konradwudkowski [Since 2.6 play-json is standalone library][1] and have no dependencies in to play. I review commints which they made directly from extraction from play code base and they didn't introduce any incompatible changes for 2.5 line, so normal eviction mechanic should work well.

I think main incompatible changes is dependency change which could lead to problem in client code. For client safety and semver sake i bumped major

[1]: https://www.playframework.com/documentation/2.7.x/Migration26#Play-JSON-moved-to-separate-project

**Review by danlaceyhmrc — COMMENTED** [review]
Hi I've been asked to approve changes to this codebase, but Im not a Scala Developer - not sure if it's because I'm on a global list or something, but I cant approve these changes !

**Comment by bambuchaAdm** [comment]
@danlaceyhmrc - probably because i put whole team in review request and Github picks you :cry: - there is issue - AIV-683 - with someone assign

**Comment by konradwudkowski** [comment]
hi @bambuchaAdm play-json 2.5 and 2.6 are not binary compatibile. If we use play-json 2.6 as you did it will be selected over play-json 2.5 in a play 2.5 microservice and this may fail with AbstractMethodError or similar at runtime

**Comment by bambuchaAdm** [comment]
>[info] play-json: found 315 potential binary incompatibilities while checking against com.typesafe.play:play-json_2.11:2.5.12

I will prepare cross compilation for different version of play

**Comment by bambuchaAdm** [comment]
Cross compile with 2.5 and 2.6 - back into major 5 in this case.

**Pull request merged**
